[package]
name = "control-flow"
version = "0.1.0"
authors = ["tragedyhk <alex99hk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rayon = "1.4.1"